ORGANIZATION_VIEW = "organization.view"
ORGANIZATION_CREATE = "organization.create"
ORGANIZATION_UPDATE = "organization.update"
ORGANIZATION_MEMBERS_VIEW = "organization.members.view"
ORGANIZATION_MEMBERS_MANAGE = "organization.members.manage"
ORGANIZATION_ROLES_VIEW = "organization.roles.view"
ORGANIZATION_ROLES_MANAGE = "organization.roles.manage"
ORGANIZATION_PERMISSIONS_VIEW = "organization.permissions.view"
ORGANIZATION_SWITCH = "organization.switch"

ALL_ORGANIZATION_PERMISSIONS = (
  ORGANIZATION_VIEW,
  ORGANIZATION_CREATE,
  ORGANIZATION_UPDATE,
  ORGANIZATION_MEMBERS_VIEW,
  ORGANIZATION_MEMBERS_MANAGE,
  ORGANIZATION_ROLES_VIEW,
  ORGANIZATION_ROLES_MANAGE,
  ORGANIZATION_PERMISSIONS_VIEW,
  ORGANIZATION_SWITCH,
)