"""create material requisitions tables

Revision ID: 9084c2019a75
Revises: a29fc475f44a
Create Date: 2026-08-22 05:30:51.947991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9084c2019a75'
down_revision: Union[str, None] = 'a29fc475f44a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material_requisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('requisition_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='material_requisition_priority'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', 'PARTIALLY_FULFILLED', 'FULFILLED', 'CANCELLED', name='material_requisition_status'), nullable=False),
    sa.Column('needed_by', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_material_requisitions_org_status', 'material_requisitions', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_material_requisitions_organization_id'), 'material_requisitions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_material_requisitions_priority'), 'material_requisitions', ['priority'], unique=False)
    op.create_index(op.f('ix_material_requisitions_project_id'), 'material_requisitions', ['project_id'], unique=False)
    op.create_index('ix_material_requisitions_project_status', 'material_requisitions', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_material_requisitions_requested_by'), 'material_requisitions', ['requested_by'], unique=False)
    op.create_index(op.f('ix_material_requisitions_requisition_number'), 'material_requisitions', ['requisition_number'], unique=True)
    op.create_index(op.f('ix_material_requisitions_status'), 'material_requisitions', ['status'], unique=False)
    op.create_table('material_requisition_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requisition_id', sa.UUID(), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('material_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('approved_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('fulfilled_quantity', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('approved_quantity <= requested_quantity', name='ck_material_req_approved_qty_lte_requested'),
    sa.CheckConstraint('approved_quantity >= 0', name='ck_material_req_approved_qty_nonnegative'),
    sa.CheckConstraint('fulfilled_quantity <= approved_quantity', name='ck_material_req_fulfilled_qty_lte_approved'),
    sa.CheckConstraint('fulfilled_quantity >= 0', name='ck_material_req_fulfilled_qty_nonnegative'),
    sa.CheckConstraint('requested_quantity > 0', name='ck_material_req_requested_qty_positive'),
    sa.ForeignKeyConstraint(['requisition_id'], ['material_requisitions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requisition_id', 'item_code', name='uq_material_requisition_item_code')
    )
    op.create_index(op.f('ix_material_requisition_items_requisition_id'), 'material_requisition_items', ['requisition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_material_requisition_items_requisition_id'), table_name='material_requisition_items')
    op.drop_table('material_requisition_items')
    op.drop_index(op.f('ix_material_requisitions_status'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_requisition_number'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_requested_by'), table_name='material_requisitions')
    op.drop_index('ix_material_requisitions_project_status', table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_project_id'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_priority'), table_name='material_requisitions')
    op.drop_index(op.f('ix_material_requisitions_organization_id'), table_name='material_requisitions')
    op.drop_index('ix_material_requisitions_org_status', table_name='material_requisitions')
    op.drop_table('material_requisitions')
    # ### end Alembic commands ###