"""add site operations

Revision ID: a29fc475f44a
Revises: d7ef21718902
Create Date: 2026-08-21 09:51:42.844305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29fc475f44a'
down_revision: Union[str, None] = 'd7ef21718902'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'REVIEWED', 'RETURNED', 'APPROVED', name='site_log_status'), nullable=False),
    sa.Column('weather', sa.Enum('SUNNY', 'PARTLY_CLOUDY', 'CLOUDY', 'RAIN', 'HEAVY_RAIN', 'STORM', 'EXTREME_HEAT', 'OTHER', name='weather_condition'), nullable=True),
    sa.Column('weather_notes', sa.Text(), nullable=True),
    sa.Column('workers_count', sa.Integer(), nullable=False),
    sa.Column('work_completed', sa.Text(), nullable=True),
    sa.Column('material_summary', sa.Text(), nullable=True),
    sa.Column('equipment_summary', sa.Text(), nullable=True),
    sa.Column('progress_percent', sa.Float(), nullable=False),
    sa.Column('blockers', sa.Text(), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('submitted_by_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'report_date', name='uq_site_log_project_report_date')
    )
    op.create_index(op.f('ix_site_logs_project_id'), 'site_logs', ['project_id'], unique=False)
    op.create_index('ix_site_logs_project_report_date', 'site_logs', ['project_id', 'report_date'], unique=False)
    op.create_index('ix_site_logs_project_status', 'site_logs', ['project_id', 'status'], unique=False)
    op.create_index(op.f('ix_site_logs_status'), 'site_logs', ['status'], unique=False)
    op.create_table('site_log_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_log_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=150), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_log_id'], ['site_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    op.create_index(op.f('ix_site_log_attachments_site_log_id'), 'site_log_attachments', ['site_log_id'], unique=False)
    op.create_table('site_log_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('site_log_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='site_issue_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', name='site_issue_status'), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_log_id'], ['site_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_site_log_issues_site_log_id'), 'site_log_issues', ['site_log_id'], unique=False)
    op.create_index(op.f('ix_site_log_issues_status'), 'site_log_issues', ['status'], unique=False)
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_milestones_id'), table_name='milestones')
    op.drop_index(op.f('ix_project_members_id'), table_name='project_members')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_project_members_id'), 'project_members', ['id'], unique=False)
    op.create_index(op.f('ix_milestones_id'), 'milestones', ['id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.drop_index(op.f('ix_site_log_issues_status'), table_name='site_log_issues')
    op.drop_index(op.f('ix_site_log_issues_site_log_id'), table_name='site_log_issues')
    op.drop_table('site_log_issues')
    op.drop_index(op.f('ix_site_log_attachments_site_log_id'), table_name='site_log_attachments')
    op.drop_table('site_log_attachments')
    op.drop_index(op.f('ix_site_logs_status'), table_name='site_logs')
    op.drop_index('ix_site_logs_project_status', table_name='site_logs')
    op.drop_index('ix_site_logs_project_report_date', table_name='site_logs')
    op.drop_index(op.f('ix_site_logs_project_id'), table_name='site_logs')
    op.drop_table('site_logs')
    # ### end Alembic commands ###